### ISSUE TITLE
Non Beta Version

### ISSUE THREAD

**Issue by tb-mtg** [wangkanai/Detection#104]
Nice project!

Just a question - why are all the releases BETA versions. 

Do you plan to release a non-beta version that can be easily searched in nuget packages without "include prerelease" being checked?

**Comment by wangkanai** [comment]
Yes, but there is still bugs that I have not had time iron out yet.

**Comment by doogdeb** [comment]
You mentioned back in April that you haven't had time to fix some bugs which are stopping you from moving out of beta. Is that still the case? I'm thinking of using your package in an Asp.Net Core application so wondering if safe to do so?

**Comment by wangkanai** [comment]
I'm using it in my production website https://sathai.com with 10K daily visitors. While I'm keeping track of error with Application Insights and its been working acceptable from me.

You can a try and see if it work out.

**Comment by wangkanai** [comment]
If 2.0-beta14 battle tested on my site without any problems for a few days, or no body rise an bug issue for this beta release. Then i would release this as non beta version.
