### ISSUE TITLE
nuget version- update to beta 10

### ISSUE THREAD

**Issue by Nazgaul** [wangkanai/Detection#105]
Hi.
Can you please update the specific nuget packges to version beta 10.
in Wangkanai.Detection.Crawler - beta 9 there is an issue with user agent Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/) which got fixes in beta 10.
Can you ship this update as well?

**Comment by wangkanai** [comment]
Beta10 is publish already duo, but it’s rank low maybe semantics version.

I’ll what can be done to fix it.

**Comment by Nazgaul** [comment]
Yes i can see that now. it somehow show that the beta 10 is lower version in nuget.

**Comment by Nazgaul** [comment]
Probably nuget sort the nuget packages version by string. beta9 is higher then beta10.

**Comment by wangkanai** [comment]
It’s should be fix now
