### ISSUE TITLE
Versioning of Nuget

### ISSUE THREAD

**Issue by horusin** [wangkanai/Detection#109]
Hello,

There are a problem with versioning in Nuget. If you release 2.0.0-beta12, nuget not recognize as higer version because nuget order of semver component are alphanumeric.

If you have 2.0.0-beta-02, then 2.0.0-beta-12 is more recent, but 2.0.0-beta-2 not function properly.

Now, you may change all packages to 2.0.1-beta-01 or 2.0.1-beta01 to correct packages.

Thanks!

![Wankamai](https://user-images.githubusercontent.com/441738/57092083-de687900-6d0a-11e9-8dae-97a6213e4b80.jpg)

**Comment by wangkanai** [comment]
I will relist them as 2.0.0-beta0X later this weekend.

**Comment by wangkanai** [comment]
I have reorganize the nuget package listing now.

![image](https://user-images.githubusercontent.com/10666633/57140444-fd860a00-6de1-11e9-9e2c-552224b655bf.png)
