### ISSUE TITLE
Responsive demo not working?

### ISSUE THREAD

**Issue by basmithy** [wangkanai/Detection#113]
Hi I'm trying to run your responsive demo, but it doesn't seem to be detecting the device?

![Capture](https://user-images.githubusercontent.com/37618806/57620197-f7312400-757f-11e9-973a-fc6116a42700.PNG)

Haven't changed any code, just built and run

**Comment by wangkanai** [comment]
Beta 11 has a bug, you would need to use beta 04 until beta 12 release.
https://www.nuget.org/packages/Wangkanai.Responsive/2.0.0-beta04

**Comment by wangkanai** [comment]
Tracking with #107
