### ISSUE TITLE
Responsive Razor Pages

### ISSUE THREAD

**Issue by rpgkaiser** [wangkanai/Detection#115]
It would be great to have the Responsive Middleware working for Razor Pages too.

**Comment by wangkanai** [comment]
should be working, let me check on that feature later in the week.

**Comment by csandoy** [comment]
any news?

**Comment by wangkanai** [comment]
need to investigate what Razor Page using differently from from Mvc for `RazorViewEngineOptions` to configure `ViewLocationExpanders`

**Comment by wangkanai** [comment]
I have got it working with layout view.

### Mobile view
![image](https://user-images.githubusercontent.com/10666633/70230489-03363a80-178b-11ea-90e4-30c2e68d1d91.png)
### Tablet view
![image](https://user-images.githubusercontent.com/10666633/70230512-1517dd80-178b-11ea-8aeb-0861de0732ee.png)
### Desktop default
![image](https://user-images.githubusercontent.com/10666633/70230563-2fea5200-178b-11ea-821f-0327b608c620.png)

**Comment by wangkanai** [comment]
Anybody got any idea how to parse the root Page folder for index?

```
foreach (var location in viewLocations)
{
    if (location.ToLower().Contains("pages"))
    {
        yield return location.Replace("{0}", "{0}." + device.Type.ToString());
        yield return location;
    }
    else
    {
        if (_format == ResponsiveViewLocationFormat.Subfolder)
            yield return location.Replace("{0}", device.Type.ToString() + "/{0}");
        else
            yield return location.Replace("{0}", "{0}." + device.Type.ToString());
        yield return location;
    }
```

**Comment by rpgkaiser** [comment]
The hard issue to resolve with Razor Pages is getting the right page(according to the device) to handle the request. Any other view (or partial view) to render after that point is working as expected.

**Comment by wangkanai** [comment]
There must be an intelligent way to resolve this. I don't have the time to focus on this yet.
Maybe somebody to could take up the challenge before i can come by and resolve this.

**Comment by wangkanai** [comment]
Need to investigate more on this concept
```csharp
builder.Services.Configure<RazorPagesOptions>(options =>
{
    options.Conventions.AddPageRouteModelConvention("index", a => a.AreaName = "detection");
    options.Conventions.AddPageRouteModelConvention("preference", a => a.AreaName = "preference");
});
```

**Comment by wangkanai** [comment]
> The hard issue to resolve with Razor Pages is getting the right page (according to the device) to handle the request (routing). Any other view (or partial view) to render after that point should works as expected.
> I think the `ViewLocationExpanders` isn't used during this first step, instead we need to figure out some way to hook up into the routing to achieve this.
> To workaround this, i used the URL Rewriting to redirect to a device specific page, if existent.

Do you have example of your url rewriting? Much appreciated.

**Comment by rpgkaiser** [comment]
Sure, here is:
`public class Startup
{
	public Startup(IConfiguration configuration, IHostingEnvironment env)
	{
		Configuration = configuration;
		HostingEnvironment = env;
	}

	public IConfiguration Configuration { get; }
	public IHostingEnvironment HostingEnvironment { get; }

	// This method gets called by the runtime. Use this method to add services to the container.
	public void ConfigureServices(IServiceCollection services)
	{
		//Configure detection services
		services.AddDetectionCore()
				.AddDevice();
		services.AddResponsive();

		services.AddMvc()
			.AddRazorPagesOptions(options => {
				options.Conventions.AuthorizePage("/Index");
			})
			.SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
	}

	// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
	public void Configure(IApplicationBuilder app, IHostingEnvironment env)
	{
		if (env.IsDevelopment())
		{
			app.UseDeveloperExceptionPage();
			app.UseDatabaseErrorPage();
		}
		else
		{
			app.UseExceptionHandler("/Error");
			app.UseHsts();
		}

		//Use responsive detection middleware
		//- detected device suffix path: *views/[controller]/[action]/index.{Desktop|Tablet|Mobile|Tv|Console|Car}.cshtml*
		//- detected device subfolder path: *views/[controller]/[action]/{Desktop|Tablet|Mobile|Tv|Console|Car}/index.cshtml*
		app.UseResponsive();

		var rewOpts = new RewriteOptions();
		rewOpts.Add(new DeviceAreaRule());
		app.UseRewriter(rewOpts);

		app.UseMvcWithDefaultRoute();
		app.UseCookiePolicy(); //Put this here, because there is an issue with the TempData if this is used before the UseMvc.
	}
}

internal class DeviceAreaRule : IRule
{
	private static readonly DeviceType[] SupportedDevices 
		= new DeviceType[] {
				DeviceType.Mobile
			//	DeviceType.Tablet
			};

	private static readonly IEnumerable<string> ExcludedPathPatterns
		= new string[] {
			  "/^Identity/.*$"
		  };

	private static readonly IEnumerable<string> IncludedPathPatterns 
		= new string[] {
			  "^/(Index)?$",
			  "^/Programs/.+$"
		  };

	public void ApplyRule(RewriteContext context)
	{
		var device = context.HttpContext.GetDevice();
		if (SupportedDevices.Contains(device) //Is a supported device, so we should have an Area for this device
			&& !IsExcluded(context.HttpContext.Request.Path) //Requested path isn't excluded
			&& IsIncluded(context.HttpContext.Request.Path) //Requested path is included
			&& !context.HttpContext.Request.Path.StartsWithSegments($"/{device}")) //Request path don't start already with the "/{device}" segment
		{
			var currUrl = context.HttpContext.Request.GetRawUrl();
			var deviceUrl = new UriBuilder(currUrl);
			var currPath = context.HttpContext.Request.Path;
			deviceUrl.Path = currPath.Value == "/"
							 ? new PathString($"/{device}")
							 : new PathString($"/{device}").Add(currPath);
			context.HttpContext.Response.Redirect(deviceUrl.ToString());
		}
	}

	private bool IsExcluded(string requestPath)
	{
		return ExcludedPathPatterns.Any(pattrn => Regex.IsMatch(requestPath, pattrn, RegexOptions.IgnoreCase));
	}

	private bool IsIncluded(string requestPath)
	{
		return IncludedPathPatterns.Any(pattrn => Regex.IsMatch(requestPath, pattrn, RegexOptions.IgnoreCase));
	}
}`

**Comment by wangkanai** [comment]
@rpgkaiser Thank you very much,
Its look very interesting how is `IRule` and `UseRewriter()` to the pages.
But what is your pages file name and extension like? is it a suffix or subfolder.

![image](https://user-images.githubusercontent.com/10666633/73861775-18eddc00-4870-11ea-982a-62a267ba3a99.png)

**Comment by rpgkaiser** [comment]
The intention with this rewriting rule is changing the area portion of the URL.
We decided to create a whole area (one per supported device) to which redirect to.
So, whe the client navigates to "~/Page" our app redirect to "~/Mobile/Page", because our app have an Area named "Mobile".

**Comment by wangkanai** [comment]
It’s make sense and easier to look solve the problem. Sorry, for asking in more detail, I like to get a better understanding and how to find best solution to the problem.

1. How do you manage with PageModel and page codes?
2. Are the page code separate per device?
3. How so you manage shared common page code for UI between devices?

**Comment by rpgkaiser** [comment]
The main (and maybe the only one) problem with Razor Pages is to determine what page to associate with the HTTP request, due to in Razor Pages, C# code and Razor code are tightly coupled. 
From that point, any other partial view to render works as expected, using the `ViewLocationExpanders` this library provide.

**Comment by wangkanai** [comment]
@rpgkaiser you in luck #297 Responsive Razor Pages view location expander is coming along with good progress.

![image](https://user-images.githubusercontent.com/1430011/74215182-15ce6380-4c55-11ea-8777-45899d409220.png)

Still have issue with Razor pages for Areas and the PR could be merged in the main branch.

**Comment by rpgkaiser** [comment]
Great news!

**Comment by rpgkaiser** [comment]
Great news!

**Comment by wangkanai** [comment]
Got a working concept with responsive razor pages using areas coming in with PR #339.

## mobile

![image](https://user-images.githubusercontent.com/10666633/74511292-46095100-4f38-11ea-9cf9-381e554883e6.png)

## tablet

![image](https://user-images.githubusercontent.com/10666633/74511255-2eca6380-4f38-11ea-9526-5eaa2a886da3.png)

Finally feature completed with PR #297
