### ISSUE TITLE
Device type showing up as "Desktop" on an Amazon Fire tablet

### ISSUE THREAD

**Issue by twonjosh** [wangkanai/Detection#116]
### Describe the bug
Device type showing up as "Desktop" on an Amazon Fire tablet

**Comment by wangkanai** [comment]
What is the user agent?

**Comment by twonjosh** [comment]
Mozilla/5.0 (Linux; Android 5.1.1; KFAUWI) AppleWebKit/537.36 (KHTML, like Gecko) Silk/77.2.19 like Chrome/77.0.3865.92 Safari/537.36

Thanks!!

**Comment by wangkanai** [comment]
Don't like it, but i have a quick fix
https://answers.microsoft.com/en-us/windows/forum/windows_10-security-winpc/amazon-device-randomly-showing-up-on-network/4e356dde-efc8-4d1a-a4ad-6295b28b5193?page=5&auth=1
