### ISSUE TITLE
CURL and NodeRed return Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by PavanelloLeonardo** [wangkanai/Detection#118]
I am using ASP.Net Core 2.2.

When I make a request with CURL or NodeRed returns the error "Object reference not set to an instance of an object".

The error happens because UserAgent is null, to correct I put a validation on methods that use UserAgent.ToString.

I downloaded the project and compiled a version with this change and it is working, in client production.

How can I submit this change to the repository?

**Comment by wangkanai** [comment]
Please do, I would like to see how you resolve this issue too.

**Comment by wangkanai** [comment]
Please fix if error this happen with beta14 from #126 PR fix
