### ISSUE TITLE
Browser detection failing due to null in non-web app context

### ISSUE THREAD

**Issue by HK8080** [wangkanai/Detection#120]
Browser detection is failing in non-web app context (ASP.NET Core 2.2, Wangkanai.Detection v2.0.0-beta12). E.g. for mixed MVC (UI + API) app, it is failing when API is called (during initialization of types injected through DI). Similarly for integration tests when running in `TestServer` context. It is failing due to internal `NullReferenceException`. As such - registered in my Startup class and injected into IoC (`AddDetection`) - it is quite an issue, because minor feature like browser/device detection is completely breaking the whole app/web APIs.
Possible workaround is to register affected types - `IDetection` dependency injected into them - conditionally into IoC based on HTTP headers (checking `User-Agent` presence). I.e. resolving them conditionally based on header presence and use "safe" types (no relation to your package) in the contexts described. It works, but is ugly and conceptually wrong.
The problem seems to be in your `UserAgent` class, which is initialized by default constructor in these contexts, when there is no required HTTP header (not investigated in detail why etc.). Because internal `useragent` remains `null`, it leads to the exception described (see `BrowserResolver` class).
The simple fix, that seems to be working for me, is to set `useragent` field to empty string always (default constructor/field initializer). At least it worked, when I have overriden default IoC registrations with my customized, fixed ones (`UserAgentService`, `UserAgent`).

Reporting this issue (quite critical for me) for you to consider, whether it is relevant or not and to possibly reflect it in your main dev branch. Thanks.

**Comment by KrisVandermotten** [comment]
I confirm we see the same problem.

Given that the server cannot guarantee that the client will send a User-Agent header, crashing when none is present is a bug. It might even be an attack vector for denial of service attacks.

The current implementation makes web applications crash when an HTTP request

**Comment by wangkanai** [comment]
It should be fix in beta 13
