### ISSUE TITLE
Yandex bot is failing ArgumentOutOfRangeException 

### ISSUE THREAD

**Issue by vovikdrg** [wangkanai/Detection#121]
### To Reproduce
Set User-Agent as Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106
##Will produce 

An exception was thrown while activating Wangkanai.Detection.Detection -> Wangkanai.Detection.BrowserResolver.
Problem Id:System.ArgumentOutOfRangeException at Wangkanai.Detection.Collections.Chrome..ctor

Will provide pull request fix in few minutes

**Comment by vovikdrg** [comment]
Maybe as a separate issue but, how about wrap BrowserResolver. GetBrowser() into try catch? I would say its way better to say I dont know what browser is that than crash. I can make PR for that too if @wangkanai approve it.

**Comment by wangkanai** [comment]
thank you @vovikdrg very much

**Comment by wangkanai** [comment]
@vovikdrg maybe you need to check if 3.0 still have this bug.

**Comment by vovikdrg** [comment]
@wangkanai Let me check. I saw some issues with other bots.

**Comment by wangkanai** [comment]
@vovikdrg Lovely, i'm await to see your good work.

**Comment by vovikdrg** [comment]
Is this there any reason you are targeting netcore 3? and not standard?

**Comment by wangkanai** [comment]
I'm not sure if this is compatible with the old asp.net core 2.x or not.
You could help me check if i change it to standard 2.0 and use with asp.net core 2.0.
:-)

**Comment by wangkanai** [comment]
> Is this there any reason you are targeting netcore 3? and not standard?

I will track the .NET Standard 2.0 issue with #237 

Let’s keep this issue with the Yandex bug.

**Comment by vovikdrg** [comment]
Ok i will look to it
