### ISSUE TITLE
Different detection of same device

### ISSUE THREAD

**Issue by djordjedjukic** [wangkanai/Detection#14]
Hi, I am using your library in ASP.NET Core MVC application. When app is open on Galaxy Tab A 2016 in firefox, device is recognized like tablet and that is OK. But when app is open in chrome or in built in browser it's recognized like desktop. Do you have some advice for that situation? Here is code example:
 
```
public class AccountController : BaseController
{
    private readonly IDevice deviceResolver;

    public AccountController(IDeviceResolver deviceResolver)
    {
        this.deviceResolver = deviceResolver.Device;
    }

     public ActionResult Login()
     {
         if (deviceResolver.Type == DeviceType.Desktop)
         {
              //some logic
         }
         else
         {
             //some logic
         }
     }
}
```

**Comment by wangkanai** [comment]
Can provide me the UserAgent of both the browser in question. I will add to the test unit.
Also does browser have desktop mode?

**Comment by djordjedjukic** [comment]
UserAgent from chrome browser from two different tablets.

Mozilla/5.0 (Linux; Android 5.0.1; 8079 Build/LRX21M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Safari/537.36

Mozilla/5.0 (Linux; Android 4.4.4; SM-T561 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Safari/537.36

**Comment by wangkanai** [comment]
Due the above user agent was not in the tablet keyword check list, so it went to the down to desktop as default.
```
private readonly string[] _tabletKeywords = {
            "tablet",
            "ipad",
            "playbook",
            "hp-tablet",
            "kindle"
        };
```

**Comment by djordjedjukic** [comment]
And your library for detecting platform still is not in function? Recognizing platform can finish job for my needs. Maybe I can make hack and expand _tabletKeywords  with word Android.

**Comment by wangkanai** [comment]
@djordjedjukic if you add the word Android to this tablet keyword that would a make all android device detected as tablet, which including mobile phone. The word “sm-t” would do a better job.

**Comment by wangkanai** [comment]
[Alcatel Pixi 10](http://www.tera-wurfl.com/explore/?action=wurfl_id&id=alcatel_8079_ver1) has only model build number as device identification, which is not suitable for resolver. So Alcatel tablet shall be drop for desktop resolver results.

**Comment by djordjedjukic** [comment]
Great, I didn't have time to make pull request. Thank you @wangkanai
