### ISSUE TITLE
Device TagHelper include & exclude render view

### ISSUE THREAD

**Issue by wangkanai** [wangkanai/Detection#23]
To helper with use the detection service in render view. TagHelper is easy to make this happen.
```
<device include="mobile">
    <h3>Detection on Home give mobile result</h3>
</device>
<device exclude="mobile">
    <h3>Detection on Home give anything not mobile as the result</h3>
</device>
```
Opening in mobile will render the following
```
<h3>Detection on Home give mobile result</h3>
```
Opening on tablet or desktop will render the following
```
<h3>Detection on Home give anything not mobile as the result</h3>
```

**Comment by wangkanai** [comment]
868d0dd64d4521b491ba1628303916171077aea1 is not highlight tag helper in razor view

**Comment by pmansoorktr** [comment]
tablet version of Android is detecting as Desk top version

**Comment by wangkanai** [comment]
@pmansoorktr because the tag helper is not highlighting, something wrong with it.

**Comment by wangkanai** [comment]
Moving to another library where it will focus on the UI part.
https://github.com/wangkanai/Responsive/pull/13
