### ISSUE TITLE
.NET Standard 2.0 compatibility

### ISSUE THREAD

**Issue by wangkanai** [wangkanai/Detection#237]
Need to validate if Detection 3.0 is backward compatible with .NET Standard 2.0 or not. So that ASP.NET Core 2.X can utilize the features add in the up coming release.

@vovikdrg Maybe you like to work on this issue.

**Comment by wangkanai** [comment]
It was related to C# 8 default to .NET Core 3.0 (https://docs.microsoft.com/en-gb/dotnet/csharp/language-reference/configure-language-version)
```xml
<LangVersion>8.0</LangVersion>
<Nullable>enable</Nullable>
```
![image](https://user-images.githubusercontent.com/10666633/72946679-31f78700-3db2-11ea-94be-4736ec5b9a60.png)
I went with what work at the time. So need to check the current development can be target back to .NET Standard 2.0 and use C# 8 while not breaking anything.

**Comment by wangkanai** [comment]
Have a build successful .NET Standard 2.0 in PR #256 from branch https://github.com/wangkanai/Detection/tree/standard
Unit tests all successfully pass. But need some beta tester from both asp.net core 2.x and 3.x

**Comment by wangkanai** [comment]
I thinking this .NET standard 2.0 should be avoided for development to move forward. 
Let wangkanai.detection 2.0 be compatible with asp.net core 2.x
Anybody have reasoning statement before I move on?

**Comment by vovikdrg** [comment]
@wangkanai  I am back i can test on 2.x

**Comment by wangkanai** [comment]
@vovikdrg how was your testing?

**Comment by wangkanai** [comment]
This PR is going to far behind and lots of C# 8.0 that require .net standard 2.1 or .net core app 3.0 as target. So going back to .net standard 2.0 might not a good option anymore.

Therefore, If you like to Detection with .net standard 2.0 aka asp.net core 2.X, then please use Wangkanai.Detection 2.0
