### ISSUE TITLE
InvalidOperationException: The request reached the end of the pipeline without executing the endpoint

### ISSUE THREAD

**Issue by fanc-mso** [wangkanai/Detection#251]
In the .NET Core 3.0 dev branch, when starting the Detection web app I get:

InvalidOperationException: The request reached the end of the pipeline without executing the endpoint: 'Sandbox.Controllers.HomeController.Index (Detection)'. Please register the EndpointMiddleware using 'IApplicationBuilder.UseEndpoints(...)' if using routing.

This seems to be resolved by moving

`app.UseDetection();`

AFTER

`app.UseEndpoints(...)`

So like this:

      public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseEndpoints(endpoints =>
                             {
                                 endpoints.MapControllerRoute(
                                     name: "default",
                                     pattern: "{controller=Home}/{action=Index}/{id?}");
                                 endpoints.MapRazorPages();
                             });

            app.UseDetection();
        }

Is this a viable workaround ? Will there be an update to allow `app.UseDetection()` to be placed anywhere in the middleware pipeline ?

Many thanks

**Comment by wangkanai** [comment]
I have a fix coming with PR #249 from commit https://github.com/wangkanai/Detection/pull/249/commits/64e8a5c17de9a88a6e1fd24e4fd7c606dd0f8e28

I'm looking to merge this PR when i get user preference by today, before I release 3.0-alpha04

**Comment by wangkanai** [comment]
For above question about where show `app.UseDetection()` be, it must be before `app.UseEndpoints()`.
This is because of the middleware pipeline.
While what cause this error was because i use `app.MapWhen()` instand of `app.UseWhen()`. Sorry, its my bad for such a simple mistake.

**Comment by wangkanai** [comment]
See if [3.0-Alpha05](https://github.com/wangkanai/Detection/releases/tag/3.0-Alpha05) resolve your issue.

**Comment by fanc-mso** [comment]
3.0 Alpha05 seems to solve it, thank you

**Comment by wangkanai** [comment]
Your welcome, @fanc-mso if you find anymore issues. Please drop me another issue report. I will close this issue and mark as resolved.
