### ISSUE TITLE
Adding Middleware {app.UseDetection()} always under the red caret

### ISSUE THREAD

**Issue by holatade** [wangkanai/Detection#298]
![Capture](https://user-images.githubusercontent.com/47521235/73721598-e8e5f200-4724-11ea-8783-528e072afd03.PNG)

**Comment by wangkanai** [comment]
Which version package are are you using?

**Comment by wangkanai** [comment]
I'm guessing you are using version 2.0
Then if yes, follow the installation on master branch readme https://github.com/wangkanai/Detection/blob/master/README.md

**Comment by holatade** [comment]
No am using  version 3.1

**Comment by wangkanai** [comment]
I mean the Wangkanai.detection package version.

**Comment by holatade** [comment]
Alryt, thanks.would go through it again.

**Comment by wangkanai** [comment]
Your welcome 😊
