### ISSUE TITLE
app.UseDetection() red caret

### ISSUE THREAD

**Issue by holatade** [wangkanai/Detection#299]
installed wanhkanai with the console command : install-package Wangkanai.Detection

Added the service services.AddDetection() in my start up file,

but add the `middleware with app.UseDetection() still under the red caret
![Screenshot (3)](https://user-images.githubusercontent.com/47521235/73790257-7adf1080-47a0-11ea-8d46-2e1ca615c54c.png)
`

**Comment by wangkanai** [comment]
In your project dependencies of your project. What version of Wangkanai.Detection are you using? like in this picture;

![image](https://user-images.githubusercontent.com/10666633/73796505-f1e7c980-47df-11ea-9899-fc2e1b68fe91.png)

If 2.0.0 use `app.UseResponsive` by 2.0 installation instruction as follow;
https://github.com/wangkanai/Detection/blob/master/README.md

if 3.0.0-x then use `app.UseDetection()` by 3.0 installation instruction as follow;
https://github.com/wangkanai/Detection/blob/dev/README.md

**Comment by holatade** [comment]
Attached is a copy of the project with the startup file,Sure i did the
correct installation which is version 2.0,and the correct package
reference.Thanks for your time

**Comment by wangkanai** [comment]
Where is the attachment?

But you say 2.0.0 then use `app.UseResponsive()` not `app.UseDetection()` by following installation instruction as follow;
https://github.com/wangkanai/Detection/blob/master/README.md

**Comment by holatade** [comment]
Thanks the version 3.0.. later worked for me.But Sumhow Version 2.0
doesnt even when i use app.UseResponsive() ,is still under the red carret;

**Comment by wangkanai** [comment]
Your welcome, for version 3.0 is the current development.

For version 2.0 things are a bit messy.

## Installation

Installation of detection library is now done with a single package reference point.

```powershell
PM> install-package Wangkanai.Detection
```

Installation of Responsive library will bring in all dependency packages (This will include `Wangkanai.Detection.Device).

```powershell
PM> install-package Wangkanai.Responsive
```

## Configuration

This library host the component to resolve the access client device type.

Implement of the library into your web application is done by configuring the `Startup.cs` by adding the detection service in the `ConfigureServices` method.

```csharp
public void ConfigureServices(IServiceCollection services)
{
	// Add detection services container and device resolver service.
    services.AddDetection();

    // Add framework services.
    services.AddMvc();
}
```

* `AddDetection()` Adds the detection services to the services container.

If you would like to add Responsive is configured in the `ConfigureServices` method also:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    // Add responsive services.
    services.AddResponsive();

    // Add framework services.
    services.AddMvc();  
}
```
Or you can customize the responsive
```csharp
public void ConfigureServices(IServiceCollection services)
{
    // Add responsive services.
    services.AddResponsive(options =>
    {
        options.View.DefaultTablet = DeviceType.Desktop;
        options.View.DefaultMobile = DeviceType.Desktop;
        options.View.DefaultDesktop = DeviceType.Desktop;
    });

    // Add framework services.
    services.AddMvc();  
}
```
* `AddResponsive()` Adds the Responsive services to the services container.

  * **Suffix** Ex `*views/[controller]/[action]/index.mobile.cshtml*`
  * **SubFoler** Ex `*views/[controller]/[action]/mobile/index.cshtml*`

The current device on a request is set in the Responsive middleware. The Responsive middleware is enabled in the `Configure` method of *Startup.cs* file.

```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    app.UseResponsive();

    app.UseMvc(routes =>
    {
        routes.MapRoute(
            name: "default",
            template: "{controller=Home}/{action=Index}/{id?}");
    });
}
```
