### ISSUE TITLE
Platform version 

### ISSUE THREAD

**Issue by ekersale** [wangkanai/Detection#359]
### Is your feature request related to a problem? Please describe.
Would it be possible to implement the platform version. If I do not mistake we already have the platform name and processor but it would be really nice to have the platform version (win-7 / win-8 / win-10)

### Describe the solution you'd like
IPlatformService.Version

**Comment by wangkanai** [comment]
Yap, it will be on my todo list.

**Comment by ekersale** [comment]
Could you add this new Version object to IPlatformService to make it available ? 

Thank you !

**Comment by wangkanai** [comment]
Added with PR #438
