### ISSUE TITLE
HttpContext cannot be null during startup

### ISSUE THREAD

**Issue by ekersale** [wangkanai/Detection#363]
### Describe the bug
Inject IDetectionService into another service during Startup.ConfigureServices cause a System.ArgumentNullException.

### To Reproduce
1. Using this version of ASP.NET Core 3.1
2. Create a new service to inject into the DI.  Add dependency injection into that service and start the application
3. After ConfiguringService application should throw a null HttpContext exception.

`   at Wangkanai.Detection.Services.UserAgentService..ctor(IHttpContextAccessor accessor)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)`

### Expected behavior
Should not generate error.

### Screenshots
![image](https://user-images.githubusercontent.com/7691499/74778290-415ed880-5269-11ea-8a6b-d4f599252523.png)

**Comment by ekersale** [comment]
Basically this implementation is just to allow you better understand whats happen. 
Because we usually only do: 
`services.AddTransient<IEventSink, SecurityLoggingEventSink>()`

I used kshyju/BrowserDetector before, and the same implementation was working fine so am pretty sure there is a workaround for the HttpContext null during startup.

**Comment by wangkanai** [comment]
Very interesting error you have got there @ekersale. Is this `IEventSink` and `SecurityLoggingEventSink` custom or open source? I would like to dig deeper into it.

**Comment by ekersale** [comment]
IEventSink is part of IdentityServer4 http://docs.identityserver.io/en/stable/topics/events.html.

SecurityLoggingEventSink  is a custom sink as describe on the documentation link. The implementation looks like the sample on the doc, with your Detection tool injected.

**Comment by wangkanai** [comment]
Thanks, i will put it on my todo list backlog to investigate later.

**Comment by fmaeseele** [comment]
Hi Guys,
I had exactly the same problem while trying to inject IDetectionService into a Service used by a IHostedService.
In such situation, there is no HttpContext at all available, since a HttpContext is related to an http request.
The workaround was to use inject IServiceScopeFactory in my service instead of IDetectionService. Then I used:
            using var scope = _serviceScopeFactory.CreateScope();
            var _detectionService = scope.ServiceProvider.GetService<IDetectionService>();

Hope that can help.

Also, this error has nothing to do with the Detection lib at all. So this issue could be closed.

**Comment by wangkanai** [comment]
@fmaeseele thank you very much 😇
