### ISSUE TITLE
assembly Wangkanai.Detection, Version=3.0.0.0 does not have a strong name

### ISSUE THREAD

**Issue by naji-makhoul** [wangkanai/Detection#364]
after upgrade to version 3.0.0.0, visual studio 2019 show me warning "Referenced assembly 'Wangkanai.Detection, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name."

![image](https://user-images.githubusercontent.com/5232373/77759933-a4047a80-7046-11ea-8d05-ed5384b2aaae.png)

**Comment by wangkanai** [comment]
Strong Name? I will investigate this later.

What is your Visual Studio 2019 update? 15.5?

**Comment by naji-makhoul** [comment]
> Strong Name? I will investigate this later.
> 
> What is your Visual Studio 2019 update? 15.5?

Visual Studio 2019 Enterprise 16.5.1

**Comment by wangkanai** [comment]
What is your csproj structure?

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Version>3.0</Version>
  </PropertyGroup>
</Project>
```

Because I'm not getting this kind of errors.
![image](https://user-images.githubusercontent.com/10666633/80226037-11bbba80-8676-11ea-8150-678eeca10bc7.png)

I'm not sure if your issue is similar to https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/1927 or not.

**Comment by naji-makhoul** [comment]
here is my csproj structure:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <AssemblyName>*******</AssemblyName>
    <RootNamespace>*******</RootNamespace>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>*******.pfx</AssemblyOriginatorKeyFile>
  </PropertyGroup>
</Project>
```


References:
```
<ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="Microsoft.AspNet.SignalR.Core" Version="2.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.Logging" Version="6.5.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.5.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.2" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.3.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.5.0" />
    <PackageReference Include="Wangkanai.Detection" Version="3.0.0-alpha09" />
    <PackageReference Include="Z.EntityFramework.Extensions.EFCore" Version="3.0.61" />
    <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="3.0.45" />
  </ItemGroup>

```

**Comment by wangkanai** [comment]
I tried to reproduce you project structure in the following branch https://github.com/wangkanai/Detection/tree/naji and still can't get the same issue.

![image](https://user-images.githubusercontent.com/10666633/80571669-37a2df80-8a27-11ea-9777-8e35ed0a7930.png)

- [ ] Code Signing
- [ ] Assemby Name
- [ ] Root Namespace
- [ ] Hosting model InProcess 

I'm really not sure that is causing your issue.

**Comment by naji-makhoul** [comment]
@wangkanai , i found it..
its happens when inject IDetectionService

try to inject it in chtml file and rebuild
```
@inject Wangkanai.Detection.Services.IDetectionService DetectionService

<p>
     Type: @DetectionService.Device.Type 
     Platform Name: @DetectionService.Platform.Name
     Browser Name: @DetectionService.Browser.Name 
     Browser Version: @DetectionService.Browser.Version
</p>

```

another way showing the worning when add it to constructor:
```
    private readonly IDetectionService _detectionService;

    public MessagingHandler(IDetectionService detectionService)
    {
        _detectionService = detectionService;
    }
```

**Comment by wangkanai** [comment]
Interesting! I can now reproduce this issue too. Its look like I would need to code sign my library before publishing it to nuget too. Would anybody like to sponsor me in code of code signing certificate? https://en.sklep.certum.pl/data-safety/code-signing-certificates/open-source-code-signing-1022.html

![image](https://user-images.githubusercontent.com/10666633/80916473-19b8e000-8d83-11ea-8b58-6ea74bc28b5d.png)

**Comment by wangkanai** [comment]
I have publish 3.0 alpha10 with code signing. See does this solve your issue.
https://www.nuget.org/packages/Wangkanai.Detection/3.0.0-alpha10

**Comment by naji-makhoul** [comment]
No , the warning still exists

> 2>CSC : warning CS8002: Referenced assembly 'Wangkanai.Detection, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```

<ItemGroup>
    <PackageReference Include="Wangkanai.Detection" Version="3.0.0-alpha10" />
  </ItemGroup>
```

**Comment by wangkanai** [comment]
:( Back to the drawing board.

Thank you

**Comment by wangkanai** [comment]
I think this issue should have been resolved a while back already. I have a code signing in place and string naming.
