### ISSUE TITLE
Can't find UseDetection method

### ISSUE THREAD

**Issue by shafaqat309** [wangkanai/Detection#368]
I am using .net core 3.1 and getting error on the line when I register app.UseDetection(), 

![image](https://user-images.githubusercontent.com/2289283/80205422-f056d080-866d-11ea-86b6-e9e493a3dbf5.png)

**Comment by wangkanai** [comment]
`UseDetection()` is a 3.0 feature. Look like you referencing 2.0.

**Comment by shafaqat309** [comment]
version 3 is in beta, what is the plan to release a tested version?

**Comment by wangkanai** [comment]
After some time to battle test and increase the performance matrix of the library. I would like to release the preview in this summer.
