### ISSUE TITLE
Unable to detect anything

### ISSUE THREAD

**Issue by randysimplist** [wangkanai/Detection#373]
### Describe the bug
Not able to detect any kind of browser, manufacturer or version. Using Wangkanai.Detection v2.0.0.

### To Reproduce
`services.AddDetectionCore().AddDevice().AddBrowser();`

### Expected behavior
`IBrowserResolver.Name` and `IBrowserResolver.Maker` should not be null.

### Additional context
I've been using this module for quite some time but I've never been able to get it to detect anything. I must be overlooking something simple. Is there anything else I need to do to get it to properly detect anything?

**Comment by wangkanai** [comment]
@Version 2.0 still have lot of issues, and i got most of this is completed in 3.0
