### ISSUE TITLE
The type or namespace name 'Services' does not exist in the namespace 'Wangkanai.Detection'

### ISSUE THREAD

**Issue by tripleacoder** [wangkanai/Detection#378]
In Blazor, I have added the Nuget package Wangkanai.Detection 2.0.0

When I add the line

```
[Inject]
        private Wangkanai.Detection.Services.IDetectionService DetectionService { get; set; }
```
        
I get:

The type or namespace name 'Services' does not exist in the namespace 'Wangkanai.Detection' (are you missing an assembly reference?)

The following works:
NuGet package Wangkanai.Detection.Device 2.0.0
```

[Inject]
        private Wangkanai.Detection.IDeviceResolver DeviceResolver { get; set; }
```

**Comment by wangkanai** [comment]
#365 Detection is not yet support in Blazor.

**Comment by wangkanai** [comment]
I will close this issue and track blazor with #365

**Comment by tripleacoder** [comment]
This is in Server hosted Blazor, not Webassembly.

**Comment by wangkanai** [comment]
I had not evaluate the blazor with detection on both model server side nor web assembly. I'm right busy on other projects, so have not look into this at all. 

By the way Mircosoft build 2020 is scheduled this May 19. Need to she what .NET 5 would be like in the official LTS release.
