### ISSUE TITLE
Browser and PlatformProperties are null

### ISSUE THREAD

**Issue by yeganehaym** [wangkanai/Detection#38]
deviceService is good but other parts their property is null
I haven't tested _engineService but the other 2 parts their properties are null

**Comment by briondris** [comment]
Me too! Yeah same problem here.

**Comment by wangkanai** [comment]
Sorry, Browser, Engine, and platform doesn’t not have work solution yet.

**Comment by wangkanai** [comment]
Browser module is functional and will be release with beta7

**Comment by wangkanai** [comment]
This issue will be close and the remaining feature of platform would be tracked via #54
