### ISSUE TITLE
Ipdad Mini 5 problem.

### ISSUE THREAD

**Issue by SerkanTopkan** [wangkanai/Detection#387]
services.AddResponsive(options =>
           {
               options.View.DefaultTablet = DeviceType.Mobile;
               options.View.DefaultMobile = DeviceType.Mobile;
               options.View.DefaultDesktop = DeviceType.Desktop;
           });

Hello to everyone

I made my settings as above. But Ipad Mini 5 also comes with a Web version.

**Comment by wangkanai** [comment]
Sorry, I assume that your web version is Desktop right?

Can you help provide me with a user agent string. I would like to make unit test.

**Comment by SerkanTopkan** [comment]
I call my website with ipad 5 mini. Despite setting, destkop version instead of mobile version. My website is http://dovizmix.com/

**Comment by wangkanai** [comment]
Now lets what is the iPad 5 Mini user agent.
```
Mozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A406 Safari/8536.25
```
Waht browser are you using? Chrome, Safari, Firefox, Edge, or etc.

**Comment by SerkanTopkan** [comment]
i am using Safari.

**Comment by wangkanai** [comment]
I'm find that everything is working as expected. This is the default

![image](https://user-images.githubusercontent.com/10666633/89115273-b7ba6480-d4b0-11ea-8039-b184b40c9db1.png)

What version of Detection are you using? 2.0 or 3.0.
