### ISSUE TITLE
When I request my site with ipad mini 5, the web version comes instead of the mobile version.

### ISSUE THREAD

**Issue by SerkanTopkan** [wangkanai/Detection#392]
![WhatsApp Image 2020-08-15 at 15 22 41](https://user-images.githubusercontent.com/8192352/90312290-e81bed00-df0b-11ea-9d40-b54c174fd12b.jpeg)
Startup.cs, my settings are as follows
```csharp
 services.AddDetection(options =>
    {
        options.Responsive.DefaultTablet  =  Device.Mobile;
        options.Responsive.DefaultMobile  = Device.Mobile;
        options.Responsive.DefaultDesktop = Device.Desktop;
        
     
    });
```
Views 
Index.cshtml
Index.mobile.cshtml

i am using .net core 3

**Comment by SerkanTopkan** [comment]
Andorid table result 
![WhatsApp Image 2020-08-15 at 15 23 42](https://user-images.githubusercontent.com/8192352/90312393-d2f38e00-df0c-11ea-93c1-f69853c44949.jpeg)

**Comment by wangkanai** [comment]
Can you please provide the actual user agent string from the physical ipad mini. I really want to debug this issue. I don't have a ipad mini.

Thank you

**Comment by SerkanTopkan** [comment]
I will take this information from Ipad Mini and write it to you. 

Thank you so much.

**Comment by wangkanai** [comment]
Thank you very much and waiting for your reply.

**Comment by SerkanTopkan** [comment]
I am very very sorry. my fault. system works. My tablet's settings were incorrect. @wangkanai

**Comment by wangkanai** [comment]
Surely, no problem :-)
