### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by mwasigala** [wangkanai/Detection#394]
I get an error  
 "IApplicationBuilder does not contain a definition 'UseDetection' "
Am using Asp.net core 3.1 and  i installed Wangkanai.Detection v2.0.0

**Comment by tiberiusaugustus** [comment]
You're probably missing a package. Open the NuGet console and run the following:
`PM> install-package Wangkanai.Detection -pre`

**Comment by wangkanai** [comment]
Detection 2.0 does not have `UseDetection()`. Reference to readme of 2.0 in the master branch.

https://github.com/wangkanai/Detection/tree/master

Only you use the Responsive middleware, then you would have `UseResponsive();` for version 2.0. Detection 3.0 will merge of all project into a single library.
