### ISSUE TITLE
Detection implementation causes loss of session data

### ISSUE THREAD

**Issue by mtanml** [wangkanai/Detection#421]
Our core 3.1 app was constantly losing session data.   We found that upon removal of Detection, the issues completely ceased.   We'd like to implement Detection, so appreciate any insight into what the root issue might be.

We had no use within Razor pages... Detection was only being used within our Home controller.

Thank you

**Comment by wangkanai** [comment]
Are you using the Detection version 2.0 Release or 3.0 Alpha?

**Comment by mtanml** [comment]
We were using 2.0

**Comment by wangkanai** [comment]
Oh, thank you. The is one of the reason of the major rewrite from 2.0 to 3.0

Do you have any log to the lose session?

**Comment by mtanml** [comment]
Sorry, I'm not sure I understand the question.   We have since changed to another similar library which doesn't cause the session loss.   If we ever decide to move back to your library, I'll be sure to install 3.0 -- thanks!

**Comment by wangkanai** [comment]
Surely, your welcome and wish to see you back with 3.0 release.
