### ISSUE TITLE
Make it a netstandard 2.1 library

### ISSUE THREAD

**Issue by frankhaugen** [wangkanai/Detection#427]
The main detection logic should exist in a shared classlib that is .net standard 2.1, and has a more flexible solution, supporting both DI and manual instantiation.

The advantage here, is that a consumer of the nuget will not have to install such a big amount of dependencies, and it will give people the opportunity to use, (parts), of it in a non-DI application, (yes, there are some use-cases, like analyzing data collected over time

Let me know if what I mean is unclear

**Comment by wangkanai** [comment]
Are you talking about version 2.0 or 3.0?

- Detection 2.0 is .NET standard 2.0
- Detection 3.0 is .NET Core 3.0

The reason I went with target framework `netcoreapp3.0` was because of C# 8.0
https://weblogs.asp.net/dixin/c-8-0-in-depth-setup-c-8-0-and-net-core-3-0
I'm not sure, if I target .net standard 2.1 at this point would break my 3.0 development or not.

**Comment by frankhaugen** [comment]
.net standard 2.1, (2.1 was released quite some time ago and is C# 8 compatible: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults).

coreapp 3.0 is going to end being officially supported in march 2021: https://dotnet.microsoft.com/platform/support/policy/dotnet-core)

But come to think of it, it's probably best to start thinking of going full .net 5 soon anyway, which is going into release in two months

**Comment by wangkanai** [comment]
I have not check if my library would work correctly with .NET 5.0 yet.
So maybe I should check about compatibility with .NET standard 2.1 first.
Thank you for the head up mate.

**Comment by wangkanai** [comment]
First change testing. Not good news so far. I going to bed now.

![image](https://user-images.githubusercontent.com/10666633/93902480-c7705f80-fd21-11ea-8fd7-6758924a42f7.png)

**Comment by wangkanai** [comment]
Detection 4.0 will support .NET 5.0
