### ISSUE TITLE
Session expired in few seconds

### ISSUE THREAD

**Issue by nskinis** [wangkanai/Detection#463]
Hi.
I'm using .Net core 3 in Visual Studio and your nuget package Detection for manage web views and mobile views but i have a problem.

Using this component my session expired in few seconds. For test, I tried to remove this package from the solution and session expired in few minutes (correctly).

Do you know how to solve the problem?

Thank's and regards.

Nicola

**Comment by wangkanai** [comment]
That is unexpected behavior!? What version of detection are you using and what kind of connections is this? Do you have example code for me to have a look? Sorry for all the questions.

**Comment by SoureMaster** [comment]
Hello Wangkanai,

      I too am experiencing this problem. I performed the same test as nskinis and found that my sessions expired in a few seconds. I believe this issue relates to .Net core 3 and up. The code used is the same a what was in your example (Detection in Middleware) without responsive. 

services.AddDetection(); - ConfigureServices

app.UseDetection(); - Configure

@addTagHelper *, Wangkanai.Detection - ViewImports

**Comment by wangkanai** [comment]
What does the error look like and where I can have an examine it?
- This is build time or runtime error?
- This is MVC/Pages or Blazor WebAssembly/Server?

**Comment by SoureMaster** [comment]
**This is build time or runtime error?**  - There is no error that is produced. What happens is that the sessions is cut short to seconds instead of the normal minutes. This occurs both on development (IIS Express) and in production(IIS 10) with SSL enabled. So if I log into my website and then click on a tab to go to another page, I am bounce back to sign up again due to the session value being NULL, instead of, for example a username being the value.

**This is MVC/Pages or Blazor WebAssembly/Server?** - This is MVC Core 3.0/Razor pages on a IIS 10 server.

**Using WangKania.Dection 3.0.0-alpha14**

` public class DetectionMiddleware
    {
        private readonly RequestDelegate _next;

        public DetectionMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public async Task InvokeAsync(HttpContext context, IDetectionService detection)
        {

            if (detection.Device.Type != Device.Mobile)
                context.Response.Redirect("https://xxxxxxxx.com");

            await _next(context);            
        }
    }

     Extension method used to add the middleware to the HTTP request pipeline.
    public static class DetectionMiddlewareExtensions
    {
        public static IApplicationBuilder UseDetectionMiddleware(this IApplicationBuilder builder)
        {
            return builder.UseMiddleware<DetectionMiddleware>();
        }
    }`



`   
            services.AddDetection();
`
`            
            app.UseDetectionMiddleware();
            app.UseDetection();
            app.UseHttpsRedirection();
            app.UseWebMarkupMin();
            app.UseStaticFiles();
            app.UseRouting();
            app.UseAuthentication();
            app.UseSession();
            app.UseRequestLocalization();
            app.UseAuthorization();

            var supportedCultures = new[] { "en", "de", "pt", "da", "es", "fr", "it", "nl", "no", "el", "sv", "fi", "ja", "ru", "zh" };
            var localizationOptions = new RequestLocalizationOptions().SetDefaultCulture(supportedCultures[0]).AddSupportedCultures(supportedCultures)
                .AddSupportedUICultures(supportedCultures);

            app.UseRequestLocalization(localizationOptions);

            app.UseMvc();
            app.UseMvcWithDefaultRoute();`

**Comment by wangkanai** [comment]
Interesting, I think I have seen that same error somewhere before. But could not identify the root cause. Anybody could help me point out where is issue is cause from?

**Comment by SoureMaster** [comment]
Any updates on this issue?

**Comment by wangkanai** [comment]
Been looking but can't find it yet. Could you help me?

**Comment by ndesorden** [comment]
Hi,
the problem is session cookie is not created so session expires after seconds WHEN register your extension AFTER net core session.

So:

```
            services.AddDetection();
                        
            services.AddDistributedMemoryCache();
            
            services.AddSession(options =>
            {
                options.Cookie.Name = ".SedeElectronicaJerez.Session";
                options.Cookie.HttpOnly = true;
                options.Cookie.IsEssential = true;
            });

...

            app.UseDetection();
            app.UseSession();
```

works fine, but

```                        
            services.AddDistributedMemoryCache();
            
            services.AddSession(options =>
            {
                options.Cookie.Name = ".SedeElectronicaJerez.Session";
                options.Cookie.HttpOnly = true;
                options.Cookie.IsEssential = true;
            });

            services.AddDetection();
...
            app.UseSession();
            app.UseDetection();
```

is blocking cookie session.

Tomorrow i´ll take at look to your code.

**Comment by wangkanai** [comment]
Maybe double registration is the problem for this.

**Comment by wangkanai** [comment]
See if Detection 3.0-beta2 solve your issue. I will revisit this issue again in 4.0 release that target .NET 5.0

**Comment by SoureMaster** [comment]
Wonderful. It is working now. Thanks. Will be making a donation via opencollective.

**Comment by wangkanai** [comment]
Thank you for update @SoureMaster
