### ISSUE TITLE
Platform Version not parsed for iPad 1_4_2

### ISSUE THREAD

**Issue by kolesnick** [wangkanai/Detection#488]
I have found that platform version is not detected for iPad (it actually returns 0.0). However version information is present in User Agent.

iPad sends following user agent:
Mozilla/5.0 (iPad; CPU OS 12_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1

I believe that there is some parse corner case because for iPhones all works correctly.

**Comment by kolesnick** [comment]
Seems like the main issue is when `PlatformService` calls `ParseOsVersion(agent, "cpuiphoneos")`.
It works for some cases but for others it should be `ParseOsVersion(agent, "cpuos")`.

**Comment by wangkanai** [comment]
Thank you @kolesnick for the report. 

What version of the Detection are you using to get this error?

**Comment by kolesnick** [comment]
Sorry for delay in answer. I am using Wangkanai.Detection 3.0.0 NuGet package.

**Comment by wangkanai** [comment]
See if 4.0-beta1 fix your issue. I have just publish the package to nuget.

**Comment by wangkanai** [comment]
![image](https://user-images.githubusercontent.com/10666633/117088648-454b1d80-ad7d-11eb-8b5e-c35a26098fb4.png)

**Comment by wangkanai** [comment]
![image](https://user-images.githubusercontent.com/10666633/117559143-0c78b480-b0ad-11eb-9c94-2b694452f832.png)
