### ISSUE TITLE
iPhone 14.7.1 User-Agent treated as Mac

### ISSUE THREAD

**Issue by kolesnick** [wangkanai/Detection#501]
One of iPhones 14.7.1 has following User-Agent:

Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) WebKit/8611 (KHTML, like Gecko) Mobile/18G82 [FBAN/FBIOS;FBDV/iPhone12,3;FBMD/iPhone;FBSN/iOS;FBSV/14.7.1;FBSS/3;FBID/phone;FBLC/en_GB;FBOP/5]

OS name is detected as Mac.

Expected to be iOS.

**Comment by wangkanai** [comment]
I have resolved this bug now. Thank you for the heads up @kolesnick .

![image](https://user-images.githubusercontent.com/10666633/144942167-753b4e1f-216a-4d33-ba8e-c23feb024f23.png)
