### ISSUE TITLE
Platform Resolver

### ISSUE THREAD

**Issue by wangkanai** [wangkanai/Detection#54]
This is to track the progress of the development of Platform Resolver in Detection Service.

**Comment by avinashbattula1** [comment]
platform detection still returning null values...I am using  Wangkanai.Detection.Platform -Version 2.0.0-beta9 and Wangkanai.Detection -Version 2.0.0-beta10 nuget packages...Can you please help me on this

**Comment by MoeHamdan** [comment]
Yeah me too Platform is always null

**Comment by MoeHamdan** [comment]
It seems the PlatformResolver is not implemented yet

**Comment by afraze9** [comment]
Same here with the `null`

**Comment by wangkanai** [comment]
@afraze9 this feature will conclude in 3.0 milestone

**Comment by wangkanai** [comment]
> It seems the PlatformResolver is not implemented yet

@avinashbattula1 @MoeHamdan @afraze9 

this feature will conclude in 3.0 milestone, I have release 2.0 stable without this feature as of yet.

**Comment by wangkanai** [comment]
This feature ready testing in 3.0-Alpha03 release with PR #217.
Please try it out and give me some feedback. Also help me identify any potential bugs.

**Comment by wangkanai** [comment]
Feature completed
