### ISSUE TITLE
AddDetectionCore

### ISSUE THREAD

**Issue by wangkanai** [wangkanai/Detection#59]
In order to add single service to the web app, the current `AddDetection()` will be change to `AddDetectionCore()` and then `AddDetection()` will a new point to all if all service is required. This is due to that this library features and functions will expand to beyond what was originally planned out.

**Comment by cwhsu1984** [comment]
I just try to install this on dotnet core 3.1 and get this issue. I think the document should be updated with `AddDetectionCore()`

**Comment by wangkanai** [comment]
Why are needing to adding only the Core part?

**Comment by cwhsu1984** [comment]
I'm not saying only the core part. My real issue is that I try to use nuget on dotcore 3.1 and follow the README's guide. I try to use `AddDetection()`, and it's not able to find this function. I think the real issue is that this package is not fully support to dotnet core 3.1, right?

**Comment by wangkanai** [comment]
That is unusual, because in the [sample web app of this repo](https://github.com/wangkanai/Detection/blob/main/sample/Detection/Startup.cs) is asp.net core 3.1 and the project is working fine. You might need to recheck your using statements. Have you added `using Microsoft.Extensions.DependencyInjection;` yet?

![image](https://user-images.githubusercontent.com/10666633/97998191-60fc5800-1e1c-11eb-9cdf-4f2bcfa325e1.png)

**Comment by cwhsu1984** [comment]
My project is also dotnet core 3.1, and I already `using Microsoft.Extensions.DependencyInjection;`

![image](https://user-images.githubusercontent.com/1912413/98182859-be3df980-1f41-11eb-8153-2cf5e833452b.png)

![image](https://user-images.githubusercontent.com/1912413/98182818-a4041b80-1f41-11eb-87ce-1412a00d7ebd.png)

**Comment by wangkanai** [comment]
Are you configuring the `ConfigureServices()` or the `Configure()` of the asp.net core `Startup.cs`? Reference from the [README](https://github.com/wangkanai/Detection/blob/main/README.md).

---
This library host the component services to resolve the access client device type. To the servoces your web application is done by configuring the `Startup.cs` by adding the detection service in the `ConfigureServices` method.

```c#
public void ConfigureServices(IServiceCollection services)
{
    // Add detection services container and device resolver service.
    services.AddDetection();

    // Add framework services.
    services.AddControllersWithViews();
}
```

* `AddDetection()` Adds the detection services to the services container.

The current device on a request is set in the Responsive middleware. The Responsive middleware is enabled in the `Configure` method of `Startup.cs` file. [Make sure that you have app.UseDetection() before app.UseRouting](https://github.com/wangkanai/Detection/issues/355).

```c#
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseDetection();
    
    app.UseRouting();

    app.UseEndpoints(endpoints => endpoints.MapDefaultControllerRoute());
}
```

**Comment by wangkanai** [comment]
> My project is also dotnet core 3.1, and I already `using Microsoft.Extensions.DependencyInjection;`
> 
> ![image](https://user-images.githubusercontent.com/1912413/98182859-be3df980-1f41-11eb-8153-2cf5e833452b.png)
> 
> ![image](https://user-images.githubusercontent.com/1912413/98182818-a4041b80-1f41-11eb-87ce-1412a00d7ebd.png)

Please update to version 3.0-alpha14 also.

```powershell
PM> install-package Wangkanai.Detection -pre
```

![image](https://user-images.githubusercontent.com/10666633/98183504-d2cac380-1f3a-11eb-8dd6-8128b73dee6d.png)

**Comment by cwhsu1984** [comment]
`PM> install-package Wangkanai.Detection -pre` works. 
Thanks!

**Comment by wangkanai** [comment]
Your welcome 😄

**Comment by NickBuckland** [comment]
Hi, I'm not sure if I am miss-reading the supported platforms. Does the package support .net5.0? I have installed Wangkanai.Detection.Core, but see errors when I try to inject IDetectionService
