### ISSUE TITLE
Browser Google Chrome v63 on Windows 10 seen as Safari

### ISSUE THREAD

**Issue by wangkanai** [wangkanai/Detection#63]
### User Agent
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
```

![image](https://user-images.githubusercontent.com/10666633/36267550-c786bb12-12a6-11e8-8ce4-5a0b376f67a6.png)

**Comment by rmsutton** [comment]
I am having the same issue

**Comment by chassq** [comment]
Still an issue today. Any idea when it may be resolved?

**Comment by akozyritskiy** [comment]
Same issue here with Chrome v69 running on Windows 10 being detected as Safari.

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

This bug appears mission critical as windows 10 and chrome both are current versions which are used on most of the devices this days. 

If these two are detected incorrectly then I think most of the devs won't see much value left in this library.

Does anybody have any ideas when this can be fixed?

**Comment by Rachit43** [comment]
Fix for chrome detection has already been provided. It seems like the latest package has not been generated yet. I'm not sure when they are planning to release the latest.

**Comment by wangkanai** [comment]
the new package will be publish after PR #85 is close.
