### ISSUE TITLE
MVC Rzor PageModel .Net Core 2

### ISSUE THREAD

**Issue by arashberlin** [wangkanai/Detection#66]
Hi,

how is it possible to add IDetection to the Razor PageModel?
When I put it the e.g. IndexModel I get an error:

InvalidOperationException: Unable to resolve service for type 'Wangkanai.Detection.IDetection' while attempting to activate 'XXXXX.App.Pages.IndexModel'.

public class IndexModel : PageModel
{
        private readonly IDetection _detection;
       private AppConfiguration _appConfig;

 public IndexModel(IOptions<AppConfiguration> appConfig, IDetection detection)
        {
            _appConfig = appConfig.Value;
            _detection = detection;
     }
      public async Task OnGetAsync(){
      ...
     }
}

**Comment by arashberlin** [comment]
found a way: 

I pout:
private readonly IBrowserResolver _browser;

and I get my info.  Great work & many thanks

**Comment by wangkanai** [comment]
Detection Service is built with Dependency Injection at the heart, so on both MVC and Razor Pages can utilize its in the constructor just fine.
But not sure which resolver are you looking to use with your second question.
Maybe you need to check out the wiki doc on which resolver or if need everything then just use the global resolver.
[https://github.com/wangkanai/Detection/wiki](https://github.com/wangkanai/Detection/wiki)
Your welcome there mate
