### ISSUE TITLE
Improve crawlers coverage

### ISSUE THREAD

**Issue by HarelM** [wangkanai/Detection#74]
Hi,
Thanks for this awesome library!
Looking at the Facebook explanation:
https://developers.facebook.com/docs/sharing/webmasters/crawler
It seems that not all of the crawlers are covered here.
Also there's a WhatsApp crawler that is named WhatsApp...
Is there a way to add strings to the crawler collection somehow? configuration file? options class?

**Comment by wangkanai** [comment]
Maybe you can help me add it to the code base.

**Comment by HarelM** [comment]
I'll be happy to help out, but there's a architectural aspect to address here which I don't want to impose. 
Whether to expand the hard coded strings, allow reading of config file or adding the ability to pass down options object.
I tend to go with the last option as it seems asp.net is going that way for most middleware and classes.

**Comment by HarelM** [comment]
Is there an alternative issue I can follow on this as the pull request doesn't really cover this issue...

**Comment by wangkanai** [comment]
You can reopen this one.

Please make it a bit clearer, maybe write some test unit to better understand what are your seek for.

**Comment by HarelM** [comment]
I would like to have something like:
```
services.AddDetection(new DetectionOptions {
    { "Whatapp", "whatsapp*" },
   ...
});

Or some thing similar so I can configure the detection with regular expressions or wildcards to support more crawlers than just what the library is currently supporting - meaning that this will be extensible using a config file/config options.

**Comment by wangkanai** [comment]
I will see for this request in version 3.0, I would likely do a rewrite of that core engine.

**Comment by wangkanai** [comment]
@HarelM  Ref PR #193 the crawler service is being rewrite. But the crawler is maintain in an Enum for strongly typed. So for something like you are suggesting will need to be added in or if contains bot and added in options would resolve to Others.

**Comment by HarelM** [comment]
Well, I'm not entirely sure how to pass the `enum` restriction, I tend to go with public const string in this case, it's much more extendable and still can be used to test the relevant crawer.
Some thing like:
```cs
public static class CrawlerTypes {
   public static readonly string FaceBook = "FaceBook"
}

...
var crawlerTest = CrawlerTypes.FaceBook == _crawlerService.CrawlerType;
```
Or maybe add another field to `ICrawlerService` - a crawler string which will be the enum to string value in case of existing crawlers and the value of the custom crawler in other cases?
Not sure...
This is how I currently use this library basically - I need to know if this is a crawler in general and the type of my custom crawler too (whatsapp):
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Services/NonApiMiddleware.cs

If you add the whatsapp crawler to this library (I can add this specifically with a PR) it will probably suites my needs and I won't need anything else, but I'm thinking on other developers as well...

**Comment by wangkanai** [comment]
This is the concept of customize able detection options for crawler.
```csharp
services.AddDetection(options =>
{
    options.Crawler.Others.Add("WhatApp");
    options.Crawler.Others.Add("MeToo");
});
```
As for adding WhatApp to the base library is also a great idea.

**Comment by wangkanai** [comment]
> Well, I'm not entirely sure how to pass the `enum` restriction, I tend to go with public const string in this case, it's much more extendable and still can be used to test the relevant crawer.
> Some thing like:
> 
> ```cs
> public static class CrawlerTypes {
>    public static readonly string FaceBook = "FaceBook"
> }
> 
> ...
> var crawlerTest = CrawlerTypes.FaceBook == _crawlerService.CrawlerType;
> ```
> 
> Or maybe add another field to `ICrawlerService` - a crawler string which will be the enum to string value in case of existing crawlers and the value of the custom crawler in other cases?
> Not sure...
> This is how I currently use this library basically - I need to know if this is a crawler in general and the type of my custom crawler too (whatsapp):
> https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Services/NonApiMiddleware.cs
> 
> If you add the whatsapp crawler to this library (I can add this specifically with a PR) it will probably suites my needs and I won't need anything else, but I'm thinking on other developers as well...

What is your `NonApiMiddleware` doing?

**Comment by wangkanai** [comment]
If you like to add more crawler to the base list, please help me add by doing a PR.

**Comment by HarelM** [comment]
My nonapimiddleware is responsible for returning a response for everything that was sent to the server that is not part of the api that the client is using.
The client routing will take care of the relevant things for the browser but not for crawlers.
So this mainly handles crawler and other non api calls - mainly to return index.html that will handle the rest.
Ill send a PR for whatsapp.

**Comment by wangkanai** [comment]
Please check out the release 3.0-Alpha02
```
Install-Package Wangkanai.Detection -Version 3.0.0-alpha02
```
Also note that their is lot of API changes coming along with 3.0, check out the sample detection application.
If you think this release doesn't solve your issue, please request to re-open this issue again.

**Comment by HarelM** [comment]
Thanks! I have added the latest pre-release to my app, initial testing on my dev machine shows the expected results.
Keep up the good work!
As a side note, I have used the `AddDetection()` method and was surprised to see that the namespace you are using is `Microsoft...` - I though I was using an incorrect extension method before understanding this is OK...

**Comment by wangkanai** [comment]
@HarelM Your welcome there mate. 
Also have you look at the ability to add others crawler to the detection options?

**Comment by wangkanai** [comment]
> My nonapimiddleware is responsible for returning a response for everything that was sent to the server that is not part of the api that the client is using.
> The client routing will take care of the relevant things for the browser but not for crawlers.
> So this mainly handles crawler and other non api calls - mainly to return index.html that will handle the rest.
> Ill send a PR for whatsapp.

Also for your `NonApiMiddleware`. You should check out the new feature i have added with PR #244. This make responsive exclude WebApi by default. You like to add to responsive you must enable it in the `DetectionOptions` like in the following.

```csharp
public void ConfigureServices(IServiceCollection services)
{
    // Add responsive services.
    services.AddDetection(options =>
    {
        options.Responsive.IncludeWebApi = true;
    });

    // Add framework services.
    services.AddControllersWithViews();
}
```

**Comment by HarelM** [comment]
@wangkanai Since whatsapp was introduced I don't have any other crawler I can test, sorry...
Regarding the `IncludeWebApi` I'm not entirely sure I understand what to do with it... but I'm sure it's useful :-)
