### ISSUE TITLE
Can compare System.Version & Wangkanai.Detection.Version

### ISSUE THREAD

**Issue by YZahringer** [wangkanai/Detection#77]
Implement IComparable on `Wangkanai.Detection.Version` to compare with `System.Version` & `Wangkanai.Detection.Version`.

**Comment by wangkanai** [comment]
@YZahringer what is the benefit of implementing IComparable? Or should we just implement System.Version

**Comment by YZahringer** [comment]
Using System.Version is better solution, it already implements IComparable.
