### ISSUE TITLE
Can you support re-write User-agent to detect manually?

### ISSUE THREAD

**Issue by minhncud** [wangkanai/Detection#82]
Because i think you don't support Responsive anymore so i write this issue here. I use MVC in ASPNET Core 2.0
I want to create a site which has a button to switch view between Mobile and Desktop. Using your Detection to handle this in server is ok but the next request i can not keep detected view.
Example:
- When I use mobile and want to **view desktop version in Index.cshtml** by clicking a button in Index.mobile.cshtml, after that, next request to my site still returns Desktop version. 
- Then when i want to return mobile version by clicking a button in Index.cshtml, it comes to Index.mobile.cshtml then next request to my site returns Mobile version.
![manual switch](https://user-images.githubusercontent.com/36953180/46328107-814efc80-c62f-11e8-9c38-b4298826d899.png)
- Page Index or About is the same Controller/Action with both Desktop or Mobile version. 
- No more parameters in About page. 
Thank you.

**Comment by wangkanai** [comment]
Can you reopen this issue in https://github.com/wangkanai/Responsive
So i could track this issue in the right place.
