### ISSUE TITLE
wangkanai/Detection ArgumentNullException: Value cannot be null.  Parameter name: Context

### ISSUE THREAD

**Issue by Aneeq0786** [wangkanai/Detection#83]
@wangkanai Am trying to use wangkanai/Detection in .net core 2.0 and followed all steps mentioned on [https://github.com/wangkanai/Detection](this link). but am getting exception and unable to start my project. any help would be appreciated. here am attachinh browser screenshot.
<img width="960" alt="issue" src="https://user-images.githubusercontent.com/43803597/46393197-9db96a80-c6fd-11e8-9621-8e82236b658c.png">

**Comment by wangkanai** [comment]
Why is your Context null? this is by design to throw an exception.

**Comment by Aneeq0786** [comment]
@wangkanai  I resolved this issue long ago unfortunatly don't remember the solution.you can close this question.

**Comment by wangkanai** [comment]
Ok then, thank you.
