### ISSUE TITLE
System.ArgumentOutOfRangeException: Length cannot be less than zero.

### ISSUE THREAD

**Issue by MohammadAkbari** [wangkanai/Detection#86]
I use beta-8 version, must of my site traffic is mobile, sometime this exception throw.

`System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length at System.String.Substring(Int32 startIndex, Int32 length) at Wangkanai.Detection.CrawlerResolver.GetCrawler() at Wangkanai.Detection.CrawlerResolver..ctor(IUserAgentService service) at lambda_method(Closure , ServiceProviderEngineScope ) at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope) at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType) at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired) `

**Comment by wangkanai** [comment]
Do you have the useragent? I would lilke to make test unit on this.

**Comment by MohammadAkbari** [comment]
I don't know, sometimes this error occurs, my opinion is to add try catch.

**Comment by wangkanai** [comment]
Looking at your error say its `ArgumentOutOfRangeException` in the `GetCrawler()`
I like a useragent to test this out to fix the bug.

**Comment by yuri-martynov** [comment]
The same issue with PayPal IPN.
Can we just ignore any detection for API requests?

**Comment by wangkanai** [comment]
Is there a way to that this controller request is api to ignore detection?

**Comment by wangkanai** [comment]
Post-it
https://www.devtrends.co.uk/blog/conditional-middleware-based-on-request-in-asp.net-core

**Comment by vovikdrg** [comment]
Looks like PR https://github.com/wangkanai/Detection/pull/91 should fix this
