### ISSUE TITLE
Failed method	Wangkanai.Detection.Collections.InternetExplorer..ctor

### ISSUE THREAD

**Issue by vovikdrg** [wangkanai/Detection#90]
I am getting errors with activating Objects. 
I've pushed update to azure to record headers as soon as I have more info, I will provide it.

> 
> 
> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = Detection (ReflectionActivator), Services = [Wangkanai.Detection.IDetection], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = BrowserResolver (ReflectionActivator), Services = [Wangkanai.Detection.IBrowserResolver], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Wangkanai.Detection.IUserAgentService)' on type 'BrowserResolver'. ---> Object reference not set to an instance of an object. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = BrowserResolver (ReflectionActivator), Services = [Wangkanai.Detection.IBrowserResolver], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Wangkanai.Detection.IUserAgentService)' on type 'BrowserResolver'. ---> Object reference not set to an instance of an object. (See inner exception for details.) (See inner exception for details.) An exception was thrown while invoking the constructor 'Void .ctor(Wangkanai.Detection.IUserAgentService)' on type 'BrowserResolver'. ---> Object reference not set to an instance of an object. (See inner exception for details.) Object reference not set to an instance of an object.
> --
> 
> 

> Autofac.Core.DependencyResolutionException:
>    at Autofac.Core.Resolving.InstanceLookup.Activate (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
>    at Autofac.Core.Resolving.InstanceLookup.Execute (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
>    at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
>    at Autofac.Core.Resolving.ResolveOperation.Execute (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
>    at Autofac.ResolutionExtensions.TryResolveService (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
>    at Autofac.ResolutionExtensions.ResolveOptionalService (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
>    at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService (Autofac.Extensions.DependencyInjection, Version=4.3.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
>    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService (Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at lambda_method (Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
>    at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider+<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0 (Microsoft.AspNetCore.Mvc.Core, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Core, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Core, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Core, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware+<Invoke>d__3.MoveNext (Microsoft.AspNetCore.Routing, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware+<Invoke>d__6.MoveNext (Microsoft.AspNetCore.Routing, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Flymark.Online.Web.Startup+<>c+<<Configure>b__9_4>d.MoveNext (Flymark.Online.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullFlymark.Online.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\Source\Web\Startup.csFlymark.Online.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 346)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at WebMarkupMin.AspNetCore2.WebMarkupMinMiddleware+<Invoke>d__5.MoveNext (WebMarkupMin.AspNetCore2, Version=2.5.0.0, Culture=neutral, PublicKeyToken=99472178d266584b)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware+<Invoke>d__5.MoveNext (Microsoft.AspNetCore.Localization, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Flymark.Online.Web.Utility.Middleware.DomainMiddleware+<Invoke>d__3.MoveNext (Flymark.Online.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullFlymark.Online.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\Source\Web\Utility\Middleware\DomainMiddleware.csFlymark.Online.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 42)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext (Microsoft.AspNetCore.Authentication, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Flymark.Online.Web.Utility.Middleware.FlymarkExceptionMiddleware+<Invoke>d__3.MoveNext (Flymark.Online.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullFlymark.Online.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\Source\Web\Utility\Middleware\FlymarkExceptionMiddleware.csFlymark.Online.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 31)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Flymark.Online.Web.Utility.Middleware.FlymarkExceptionMiddleware+<Invoke>d__3.MoveNext (Flymark.Online.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullFlymark.Online.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\Source\Web\Utility\Middleware\FlymarkExceptionMiddleware.csFlymark.Online.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 42)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Anemonis.AspNetCore.RequestDecompression.RequestDecompressionMiddleware+<Microsoft-AspNetCore-Http-IMiddleware-InvokeAsync>d__3.MoveNext (Anemonis.AspNetCore.RequestDecompression, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass5_1+<<UseMiddlewareInterface>b__1>d.MoveNext (Microsoft.AspNetCore.Http.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext (Microsoft.AspNetCore.StaticFiles, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware+<Invoke>d__6.MoveNext (Microsoft.AspNetCore.Diagnostics, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
> Inner exception Autofac.Core.DependencyResolutionException handled at Autofac.Core.Resolving.InstanceLookup.Activate:
>    at Autofac.Core.Resolving.InstanceLookup.Activate (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
>    at Autofac.Core.Resolving.InstanceLookup.Execute (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
>    at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
>    at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
>    at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
>    at Autofac.Core.Resolving.InstanceLookup.Activate (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
> Inner exception Autofac.Core.DependencyResolutionException handled at Autofac.Core.Resolving.InstanceLookup.Activate:
>    at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
>    at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
>    at Autofac.Core.Resolving.InstanceLookup.Activate (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)
> Inner exception System.NullReferenceException handled at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate:
>    at Wangkanai.Detection.Collections.InternetExplorer..ctor (Wangkanai.Detection.Browser, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null)
>    at Wangkanai.Detection.BrowserResolver.GetBrowser (Wangkanai.Detection.Browser, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null)
>    at Wangkanai.Detection.BrowserResolver..ctor (Wangkanai.Detection.Browser, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null)
>    at lambda_method (Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
>    at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate (Autofac, Version=4.8.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da)

**Comment by vovikdrg** [comment]
Catched headers


User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36; 360Spider
-- | --

**Comment by vovikdrg** [comment]
datagnionbot (+http://www.datagnion.com/bot.html)

**Comment by vovikdrg** [comment]
@wangkanai I wanted to fix this bug but when I run tests they all fail. I am running from VS. Could you please help

**Comment by vovikdrg** [comment]
AdsBot-Google (+http://www.google.com/adsbot.html)
--

**Comment by vovikdrg** [comment]
Looks like it was fixed in beta9, since I just find out that I was using beta8..

**Comment by wangkanai** [comment]
@vovikdrg let me solid out #60 Request extension detection before i publish beta 10.
