### ISSUE TITLE
platform detection not working

### ISSUE THREAD

**Issue by ahmadhamzavi** [wangkanai/Detection#92]
hello 
i test your service with many of user agents , but service just detect the Device , not any other ,like platform .

i added  services.AddDetection(); in startup.

**Comment by wangkanai** [comment]
The the current moment dedection is working Device (since beta1) and Browser (since beta7).

For platform and engine in the roadmap for 2.0 release.

**Comment by wangkanai** [comment]
Your can track platform via #54 and engine via #53
